{"name": "Проверка невозможности создания пользователя, который уже зарегистрирован", "status": "passed", "start": 1729364085407, "stop": 1729364086344, "uuid": "ee8f202f-3757-4d83-a4f1-2f6bfb6c02f7", "historyId": "00f98fc232e2cd71a8757f3176e67b89", "testCaseId": "00f98fc232e2cd71a8757f3176e67b89", "fullName": "tests.test_user_sign_up.TestUserSignUp#test_create_user_which_already_created_user_not_created_for_the_second_time", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_sign_up"}, {"name": "subSuite", "value": "TestUserSignUp"}, {"name": "host", "value": "DESKTOP-ABCQNV2"}, {"name": "thread", "value": "12224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_sign_up"}]}